// Copyright 2024 YOLOs-CPP Team
// SPDX-License-Identifier: AGPL-3.0

#ifndef ROS2_YOLOS_CPP__CONVERSION__POSE_CONVERTER_HPP_
#define ROS2_YOLOS_CPP__CONVERSION__POSE_CONVERTER_HPP_

#include <vector>
#include <vision_msgs/msg/detection2_d_array.hpp>
#include <std_msgs/msg/header.hpp>

#include "ros2_yolos_cpp/adapters/yolos_adapter_base.hpp"
#include "ros2_yolos_cpp/visibility_control.hpp"

// Forward declare custom message (generated by rosidl)
namespace ros2_yolos_cpp { namespace msg {
class KeyPoint2DArray;
}}

namespace ros2_yolos_cpp {
namespace conversion {

/// @brief Convert PoseResults to Detection2DArray with keypoint info in id/tracking_id
ROS2_YOLOS_CPP_PUBLIC
vision_msgs::msg::Detection2DArray toDetection2DArray(
  const std::vector<PoseResult>& poses,
  const std_msgs::msg::Header& header,
  int image_width,
  int image_height);

}  // namespace conversion
}  // namespace ros2_yolos_cpp

#endif  // ROS2_YOLOS_CPP__CONVERSION__POSE_CONVERTER_HPP_
